### ISSUE TITLE
移动端页脚文字过长时出现样式错误

### ISSUE THREAD

**Issue by hifocus** [dongyuanxin/theme-ad#14]
Live demo: https://www.justhx.com/friends ，使用手机或者 Chrome 审查元素 - 模拟手机 打开。

样式错误如下图：

![image](https://user-images.githubusercontent.com/30528433/54822134-2f149d00-4c9c-11e9-9b81-e2892e4a8cc4.png)

**Comment by dongyuanxin** [comment]
样式问题，会尽快修复

**Comment by dongyuanxin** [comment]
版本[v2.4.0](https://github.com/dongyuanxin/theme-ad/releases/tag/v2.4.0)已经修复

**Comment by hifocus** [comment]
感谢作者。另外把两三个我也发现了的问题也改了，tql
