### ISSUE TITLE
希望增加 Google Custom Search 的功能并优化现有 Reward 的功能

### ISSUE THREAD

**Issue by 1an8r0wn** [dongyuanxin/theme-ad#17]
现有的搜索方式是输入关键词后直接跳转到 Google 的相关搜索结果页面。这对用户来说不太友好。Google 有提供 Google Custom Search 的功能，希望能把这个功能加入并在本站展示搜索结果而不是跳转到 Google 上。

Reward 部分。点击后，弹出的框刚好能展示微信的二维码而支付宝的二维码则是被遮挡住了。
建议集成 https://github.com/Kaiyuan/donate-page/tree/gh-pages/simple 的打赏，直接在评论区上面展示打赏，而不需要点击才展示打赏。

**Comment by hifocus** [comment]
> 现有的搜索方式是输入关键词后直接跳转到 Google 的相关搜索结果页面。这对用户来说不太友好。Google 有提供 Google Custom Search 的功能，希望能把这个功能加入并在本站展示搜索结果而不是跳转到 Google 上。
> 
> Reward 部分。点击后，弹出的框刚好能展示微信的二维码而支付宝的二维码则是被遮挡住了。
> 建议集成 https://github.com/Kaiyuan/donate-page/tree/gh-pages/simple 的打赏，直接在评论区上面展示打赏，而不需要点击才展示打赏。

个人感觉 CSE 是 Google 多年没有维护的产品了，搜索体验没有原生 Google.com 好。

此外这个 donate-page 的插件我觉得太繁复了；可以用 https://github.com/hifocus/merger 合并多个二维码到一个。

**Comment by dongyuanxin** [comment]
@1an8r0wn 正如 @hifocus 所说，cse多年不维护。除此之外，考量2个问题：
1. 整体UI设计的统一性：第三方插件的UI基本上都不吻合
2. 代码的可维护性：完全没必要为了二维码功能，再引入一个轮子

**Comment by hifocus** [comment]
> @1an8r0wn 正如 @hifocus 所说，cse多年不维护。除此之外，考量2个问题：
> 
> 1. 整体UI设计的统一性：第三方插件的UI基本上都不吻合
> 2. 代码的可维护性：完全没必要为了二维码功能，再引入一个轮子

但是我觉得现在只有 Google，可以做一个下拉，允许用户选取百度，必应，甚至可以自定义搜索引擎。用户只需要自定义 example.com/?q=xxx 这部分就好。

**Comment by dongyuanxin** [comment]
> > @1an8r0wn 正如 @hifocus 所说，cse多年不维护。除此之外，考量2个问题：
> > 
> > 1. 整体UI设计的统一性：第三方插件的UI基本上都不吻合
> > 2. 代码的可维护性：完全没必要为了二维码功能，再引入一个轮子
> 
> 但是我觉得现在只有 Google，可以做一个下拉，允许用户选取百度，必应，甚至可以自定义搜索引擎。用户只需要自定义 example.com/?q=xxx 这部分就好。

这个没问题，新开个需求的Issue？不在这个issue中讨论。

**Comment by dongyuanxin** [comment]
收入 [《Theme Art Design 主题常见问题》](https://github.com/dongyuanxin/theme-ad/blob/develop/docs/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md)
