### ISSUE TITLE
代码无法高亮

### ISSUE THREAD

**Issue by abigmiu** [dongyuanxin/theme-ad#18]
![](http://ww1.sinaimg.cn/large/006dqus4gy1g22fq4otvvj31c30l1q9d.jpg)
问题图片
http://ww1.sinaimg.cn/large/006dqus4gy1g22fq4otvvj31c30l1q9d.jpg
菜鸟，不知道怎么提交问题，解决问题

**Comment by dongyuanxin** [comment]
markdown语法需要指明高亮的语言种类，你的这种情况应该是 `css`

![image](https://user-images.githubusercontent.com/26399528/56106011-ad015680-5f71-11e9-9e3f-3c41b6f4c96c.png)

**Comment by abigmiu** [comment]
> markdown语法需要指明高亮的语言种类，你的这种情况应该是 `css`
> 
> ![image](https://user-images.githubusercontent.com/26399528/56106011-ad015680-5f71-11e9-9e3f-3c41b6f4c96c.png)

谢谢，不过指定语法类型后有的代码段可以渲染成功，有的不可以。

**Comment by dongyuanxin** [comment]
@abigmiu 比如`go`语言，在渲染方面，就会出现问题。主要集中在一些新兴语言和少人用的语言。
