### ISSUE TITLE
主题搜索栏提供多个搜索引擎选项

### ISSUE THREAD

**Issue by hifocus** [dongyuanxin/theme-ad#19]
> @1an8r0wn 正如 @hifocus 所说，cse多年不维护。除此之外，考量2个问题：
> 
> 1. 整体UI设计的统一性：第三方插件的UI基本上都不吻合
> 2. 代码的可维护性：完全没必要为了二维码功能，再引入一个轮子

但是我觉得现在只有 Google，可以做一个下拉，允许用户选取百度，必应，甚至可以自定义搜索引擎。用户只需要自定义 example.com/?q=xxx 这部分就好。

_Originally posted by @hifocus in https://github.com/dongyuanxin/theme-ad/issues/17#issuecomment-482775902_

如上述内容，欢迎提出建议。

**Comment by hifocus** [comment]
可以在主题的 `_config.yaml` 内允许用户列出希望使用的搜索引擎的搜索链接，默认为用户配置好 baidu, google, bing 三项，用户可以随意调整排序或者删除不想要的搜索引擎。

可以参考 chrome://settings/searchEngines （Google Chrome 内打开）的格式：

"URL with %s in place of query"
`https://github.com/search?q=%s&ref=opensearch`

**Comment by dongyuanxin** [comment]
get

**Comment by dongyuanxin** [comment]
已经完成了，点击即可切换。

支持baidu、bing、google，同时有鼠标悬浮后的文案“Change Search Engine”作为提示。

![image](https://user-images.githubusercontent.com/26399528/58020526-f62d6300-7b3a-11e9-8cb6-80caaf24ed14.png)
