### ISSUE TITLE
建议增加文章目录侧边栏弹出后，点击主界面收起的功能

### ISSUE THREAD

**Issue by Stark-X** [dongyuanxin/theme-ad#2]
目前好像只能通过点击小箭头把侧边栏收回去

**Comment by dongyuanxin** [comment]
您说的是点击阴影，也可以收起文章目录侧边栏？

**Comment by Stark-X** [comment]
是的，这样更符合操作习惯吧

Thanks & Regards,
Stark-X
Blog: https://blog.stark-x.cn
Github: https://github.com/stark-x

**Comment by dongyuanxin** [comment]
已经实现了：[https://github.com/dongyuanxin/theme-ad/releases/tag/v1.0.0-beta.2](https://github.com/dongyuanxin/theme-ad/releases/tag/v1.0.0-beta.2)
