### ISSUE TITLE
提供选项使用 jsDelivr 合并多个 CSS 或 JS 文件到一个以减少请求数

### ISSUE THREAD

**Issue by hifocus** [dongyuanxin/theme-ad#20]
jsDelivr 提供了文件合并功能，能够合并 jsDelivr 托管的任何CSS 或者 JS 资源（npm, github, wordpress 官方仓库）到一个。

目前访客模式加载使用本主题的 https://www.justhx.com 会加载来自主题本身的 12 个 js：

![image](https://user-images.githubusercontent.com/30528433/56106507-0b2f3900-5f74-11e9-9890-d1e99133fff5.png)

以及三个 css：

![image](https://user-images.githubusercontent.com/30528433/56106521-1da97280-5f74-11e9-9bbe-1f73adff3d0f.png)

可以参考：https://github.com/hifocus/merger/blob/master/merger.html#L102 此处合并了同一个仓库内 `/assets` 目录下四个 `.js` 文件（包括了 jQuery，jQuery-qrcode，`function.js` 以及 iconfont）到一个，实际加载流量相同，但是减少了 HTTP 请求数，同时节省了服务器 / CDN 流量。

考虑到（尽管 jsDelivr 可用性非常高 且在国内速度非常好）有用户也许只希望按照原样从本地加载 css 和 js 文件，这个功能可以作为选项提供

jsDelivr 网站：https://www.jsdelivr.com
国内访问延迟：http://ping.chinaz.com/cdn.jsdelivr.net

**Comment by hifocus** [comment]
此外，jsDelivr 还可以合并来自不同源（例如 github 和 npm），不同仓库的代码。

可以参见：[https://www.justhx.com/merger-new-documentation.html#合并-js-请求
](https://www.justhx.com/merger-new-documentation.html#%E5%90%88%E5%B9%B6-js-%E8%AF%B7%E6%B1%82)

**Comment by 1an8r0wn** [comment]
我自己手动把这些JS都放到自己的repo下，然后jsdeliver合并的，不过要是能提供选项就最好了。

**Comment by dongyuanxin** [comment]
谢谢提醒，我做一下调研

**Comment by dongyuanxin** [comment]
@hifocus 目前已经支持用自定义的cdn替换第三方插件默认的cdn，你可以使用国内cdn或者自建cdn。

另外，对于合并js的想法，可以按照 @1an8r0wn 的描述尝试。不过，**并不推荐这种做法**。

主题本身针对内置 `script` 标签的加载已经做了控制与优化，如果强行使用第三方平台合并成一个js文件，可能会出现不可控bug。

**最后，如果有精力，请按照 [`常见问题.md`](https://github.com/dongyuanxin/theme-ad/blob/develop/docs/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md) 的文档格式，将此issue放入文档，帮助更多人。以发起pr的方式即可。**
