### ISSUE TITLE
修正 “阅读更多” 不正确文案

### ISSUE THREAD

**Issue by hifocus** [dongyuanxin/theme-ad#21]
https://github.com/dongyuanxin/theme-ad/blob/a5b899e6a051470e89b487ebcc74f4cb8b99ac7c/layout/index.ejs#L36

如上述文案所示，README MORE 并没有 make sense。建议修改为 READ MORE 或者按照 https://blog.google 的文案 - READ ARTICLE

效果参见 https://www.justhx.com
更新记录：[https://www.justhx.com/matters/](https://www.justhx.com/matters/) - 2019-04-09

**Comment by dongyuanxin** [comment]
这里疏忽了，是个问题。

**Comment by dongyuanxin** [comment]
@hifocus change it at [the latest commit](https://github.com/dongyuanxin/theme-ad/commit/a88bd5122ff8fa5f975e574f1fb39dbbd7410ef0)

**Comment by hifocus** [comment]
Great.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
