### ISSUE TITLE
希望能加入多语言支持

### ISSUE THREAD

**Issue by PorridgePi** [dongyuanxin/theme-ad#27]
由于我想用两个语言（中文和英语）来写博客，自己折腾了一下，可似乎挺麻烦的。看网上有人用[NexT主题](https://upwnothing.github.io/2018/09/13/Hexo-Bilingual-Blog/)做了，可以参考参考吧。

希望能加入多语言支持，谢谢！

P.S.
您的主题特别好看！

**Comment by dongyuanxin** [comment]
@Kunbao2006 
这和主题无关，每篇文章需要写两份（中英文各一份）。举个例子，你给出的网站连接中：

![image](https://user-images.githubusercontent.com/26399528/64519780-6993f400-d327-11e9-8207-e11110ac545f.png)
