### ISSUE TITLE
[bug] The *TOC* button isn't disabled actually

### ISSUE THREAD

**Issue by Stark-X** [dongyuanxin/theme-ad#3]
The *TOC* button style is "disabled" on the index page right now, but it could be clicked actually, then the main content cover layer which the *TOC* slide nav-bar triggered will come out, but the slide nav-bar doesn't.  
In this case, the customer cannot do any operation on the page, the only way back is to refresh the page.

I'm using the latest Chrome on macOS 10.14.3

**Comment by dongyuanxin** [comment]
I have fixed it at [v1.0.0-beta.2](https://github.com/dongyuanxin/theme-ad/releases/tag/v1.0.0-beta.2). 
Download and try it.
