### ISSUE TITLE
谢谢你制作的主题。请问你的博客中左边的侧边栏是怎么弄的，我使用了你的主题之后并没有左边的侧边栏。

### ISSUE THREAD

**Issue by czq-woodpecker** [dongyuanxin/theme-ad#31]

**Comment by dongyuanxin** [comment]
@czq-woodpecker 
侧边栏开关在下方的导航栏中：

![image](https://user-images.githubusercontent.com/26399528/64520015-d4ddc600-d327-11e9-90f9-d6499cdc9bd7.png)
