### ISSUE TITLE
leancloud appid, appkey and the other credentials should not contains in the repo

### ISSUE THREAD

**Issue by Stark-X** [dongyuanxin/theme-ad#4]
Your leancloud appid and appkey had been committed in the git, you should regenerate the appkey (if it's possible), or the others who accessing this repo can attack your account.

You could create a `_config.yml` with fake values, or a template named `_config.yml.template`, or some way else to hide your secrets.

**DO NOT** commit any credentials into the public repo.

**Comment by dongyuanxin** [comment]
Thanks!
But appid and appkey in `_config.yml` are **specially** prepared for using and displaying results.
**User should replace it with own appid and appkey.**
