### ISSUE TITLE
复制的时候，能否取消自动带有 copyright 的信息？

### ISSUE THREAD

**Issue by powersee** [dongyuanxin/theme-ad#41]
博主你好，非常喜欢你写的这个主题。我有一个问题想请教，文章的内容，以及代码，复制的时候，会自动带有 copyright 的信息，这对于代码的复制就会不方便了。

我想去掉这个功能，但是在主题的 comfig.yml 里面没有找可以关闭的选项。要关只能把整个 copyright 给关了。

所以想问问能否保留下方的 copyright 信息，但是复制文章内容的时候，不要自动添加这些信息到剪贴板？

期待您的回复，感谢。

**Comment by phlinhng** [comment]
要是有代碼複製功能就更好了

**Comment by powersee** [comment]
问题解决了，可以通过修改 source/js/copy.js 来达到目的。作者是设置超过 42 个字符的复制，就会自动在后面添加版权信息，将里面的函数注释了即可。
