### ISSUE TITLE
分类的bug问题

### ISSUE THREAD

**Issue by iianran** [dongyuanxin/theme-ad#43]
有两篇文章，
第一篇在添加分类的时候使用了两个词比如：学习笔记、前端。
第二篇在添加时使用了一个词：前端。 
理想中的是，应该在分类中的前端中有上述两篇文章。
事实是，分类中有显示了2个前端，每个前端里仅有一篇文章。
是没办法支持这种吗？

**Comment by leverimmy** [comment]
多个分类好像会导致 父-子目录关系
