### ISSUE TITLE
建议增加 Disqus 和 不蒜子 的支持

### ISSUE THREAD

**Issue by ghost** [dongyuanxin/theme-ad#5]
本身在 Dsiqus 上有很多评论，不想因为更换主题而丢失评论。
PV 统计建议增加 不蒜子 的支持。

**Comment by dongyuanxin** [comment]
Disqus已经在规划中，但是不蒜子并没有在规划中。

**Comment by dongyuanxin** [comment]
不蒜子加入规划。
PS：我一直以为不蒜子还在内测 TwT

**Comment by dongyuanxin** [comment]
已经完成支持，请最新版本--[v2.3.0](https://github.com/dongyuanxin/theme-ad/releases/tag/v2.3.0)

并且修改配置文件58 ~ 63行来开启 Disqus / 不蒜子
