### ISSUE TITLE
子路径访问时，相对路径资源会有问题

### ISSUE THREAD

**Issue by grace5925** [dongyuanxin/theme-ad#6]
假设我的博客地址是`https://xxx.com/blog/`，这个时候'/'开头的相对路径都会拿不到资源，hexo配置文件里面有个root配置，相对路径配上那个root就可以避免这种现象了，除了资源路径，后面发现有一处跳转也是相对路径，配上root也就没问题了

**Comment by dongyuanxin** [comment]
这个是和`Hexo`配置相关，如果使用二级路由，需要在**全局配置文件**中设置`root`属性。

例如所说的`https://xxx.com/blog/`:
```yml
root: /blog/
```

**Comment by grace5925** [comment]
我的意思是，因为全局配置文件我配置了`root`属性，所以出现了资源访问不正常的情况，我尝试改回全局`root`为`/`，本地预览是没有问题了，但是丢到线上问题还是存在的。另：想问一下置顶怎么弄？

**Comment by dongyuanxin** [comment]
1. 置顶是`hexo`插件，**和主题无关**: [hexo-generator-index](https://www.npmjs.com/package/hexo-generator-index-pin-top)
2. 请详细陈述你的报错信息，并且附上截图等说明 : )

**Comment by grace5925** [comment]
![1](https://user-images.githubusercontent.com/7194782/54071625-11adff00-42aa-11e9-8333-adcb7d618f6c.png)

我一直都有设置root属性，之前在用bmw主题的时候，也是这样的设置，但是没有出现资源无法访问的问题，下图是我在换用ad主题之后的报错信息

![2](https://user-images.githubusercontent.com/7194782/54071646-6cdff180-42aa-11e9-89b7-c5d81d2736d3.png)

出现报错我就看了一眼资源路径，从截图中也可以看出不同，相对路径有带`/blog`和不带`/blog`打头的，带`/blog`的可以正常访问，无可厚非，不带`/blog`的肯定是无法拿到资源的

**Comment by dongyuanxin** [comment]
谢谢提出，已经确定是二级路由下资源定位错误的问题。
Thanks very much @grace5925

**Comment by dongyuanxin** [comment]
我在 [hotfix/multi-route-error](https://github.com/dongyuanxin/theme-ad/tree/hotfix/multi-route-error) 分支尝试修复了这个问题，请下载此分支代码，并且使用。
如果没有问题，我会在1天内将其合并到主分支；
如果有问题，请及时反馈。

**Comment by grace5925** [comment]
感觉应该还有2处遗漏，你看下，下面上图

![1](https://user-images.githubusercontent.com/7194782/54081808-f264af80-4345-11e9-9de3-8b9b59aecdcc.png)
![2](https://user-images.githubusercontent.com/7194782/54081811-f690cd00-4345-11e9-869e-9f0a472126c2.png)

**Comment by grace5925** [comment]
@dongyuanxin 无意间看到你的作品，主题色调风格非常喜欢，感谢分享，能让我愿意提出问题的原因也就是因为喜欢，纯支持了

**Comment by dongyuanxin** [comment]
Thanks very very much for your report and patience, @grace5925 ! 
1. I have fixed it, download at [v2.1.2](https://github.com/dongyuanxin/theme-ad/releases/tag/v2.1.2)
2. I have put your name in v2.1.2 description specially

**Comment by grace5925** [comment]
╰(￣▽￣)╮
