### ISSUE TITLE
Contributing Guide Wanted

### ISSUE THREAD

**Issue by AlessandroChen** [dongyuanxin/theme-ad#7]
Hi, this theme is awesome!
But I am confused about how to contribute to this project.
Is there any Guide for those who want contribute to this project ?

**Comment by dongyuanxin** [comment]
Thx, I will write pull request template file and details in this week.

**Comment by dongyuanxin** [comment]
- [PULL_REQUEST_TEMPLATE.md](https://github.com/dongyuanxin/theme-ad/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
- [ISSUE_TEMPLATE](https://github.com/dongyuanxin/theme-ad/blob/master/.github/ISSUE_TEMPLATE.md)
