### ISSUE TITLE
期望加入全站全文搜索功能

### ISSUE THREAD

**Issue by Ennn** [dongyuanxin/theme-ad#8]
#### Do you want to request a _feature_ or report a _bug_ or just a _question_?

期望加入全站全文搜索功能。类似这个实现的：https://gaoryrt.com/
如不在计划列表，请忽略。

**Comment by dongyuanxin** [comment]
没有加入的原因有3个：
1. 风格统一的UI风格
2. 复用之前的代码, 尽量不破坏整体的架构
3. 有很多极简主义的主题是直接借助搜索引擎

我做一下调研，但目前还没有在计划表中。

**Comment by Ennn** [comment]
好的，多谢~

**Comment by 1an8r0wn** [comment]
我更加倾向于直接集成 Google Custom Search 更好。直接搜索并在站点内返回结果而不用跳出到 Google
